### ISSUE TITLE
Debugging data layer without Xcode

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Tealium/tealium-swift#162] opened 2020-11-11 12:24 UTC
How can you test the content of the data layer as a non-developer (without Xcode). If you switch a proxy tool like charles in between, you only see that the mobile.html is loaded and the Javascript code is executed. But not the content of the data layer. What is the preferred way for a QA here?
Many thanks.

**Comment by christinasund** [comment] 2020-11-11 16:14
Hi @andreas-sommer-engenious 

Here are some troubleshooting/debugging options for your mobile installation: https://docs.tealium.com/platforms/getting-started/troubleshooting/#debugging-mobile-html

Let us know if you have any questions, thanks!

**Comment by andreas-sommer-engenious** [comment] 2020-11-12 11:49
Yes I found that article too. I want to verify the datalayer with remote debugging in safari. I connected an iPhone via usb cable to my mac and enabled the remote debugging on the iPhone. What when I look in Safari->developer->iPhone then I can only see a blank page and not the mobile.html. Do you have any idea why?
Regards

**Comment by craigrouse** [comment] 2020-11-12 14:46
@andreas-sommer-engenious do you also have Charles Proxy running? If so then it's possible the certificates aren't set up properly on your device/simulator, which would cause the mobile.html page not to load. I've also had a few issues recently with Safari remote debugging, and found that using the Safari Developer Preview has solved this. I have no idea why this is the case, but assume there must be a bug in one of the recent Safari versions that's fixed in the preview. Let us know how you get on.

**Comment by andreas-sommer-engenious** [comment] 2020-11-12 14:55
Do you mean the Safari Technology Preview:
https://developer.apple.com/safari/technology-preview/

**Comment by craigrouse** [comment] 2020-11-12 14:56
Yes that's the one @andreas-sommer-engenious

**Comment by andreas-sommer-engenious** [comment] 2020-11-12 14:57
Ok, I will try it.

**Comment by andreas-sommer-engenious** [comment] 2020-11-12 15:17
No it doesn't work. Can we meet us in zoom tommorow, that I can show you the problem?

**Comment by craigrouse** [comment] 2020-11-12 15:30
Sure @andreas-sommer-engenious. I have your email address from an old ticket, so I'll drop you an email to arrange.

**Comment by andreas-sommer-engenious** [comment] 2020-11-12 15:31
You can use andreas.sommer@engenious.de or a.sommer@extern.thalia.de

**Comment by craigrouse** [comment] 2020-11-13 11:46
For future reference, the root cause of this issue was that the Remote Publish Settings option was enabled, and the Tag Management option was disabled in the Remote Publish Settings. Tag Management just needed enabling in Remote Publish Settings.

**Closed by craigrouse** 2020-11-13 11:46 UTC
