### ISSUE TITLE
[TEALIUM SWIFT BUG]: Unable to compile Tealium with Xcode12 & Carthage

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-swift#145] opened 2020-06-25 12:09 UTC
Trying to compile Tealium 1.9.5 with carthage using Xcode12 beta1 as build environment fails. Here is the log:

Undefined symbols for architecture i386:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in TealiumDiskStorage.o
ld: symbol(s) not found for architecture i386

**Comment by craigrouse** [comment] 2020-06-25 12:27
Thanks @JuhaO81. We're just having a play around with the beta ourselves too, so thanks for the early warning about this. Installation via Swift Package Manager works as expected.

**Comment by craigrouse** [comment] 2020-06-25 12:29
@JuhaO81 could I just check which build of Xcode you're using? Are you using the one designated for building Universal binaries for Apple Silicon and Intel processors, or the standard build?

**Comment by craigrouse** [comment] 2020-06-25 12:35
A quick check of the Carthage GH Issues page revealed this issue: https://github.com/Carthage/Carthage/issues/3004

This seems very similar to our issue. We'll continue to investigate 🕵️

**Comment by JuhaO81** [comment] 2020-06-25 12:37
I was compiling with "carthage update --platform iOS"

**Comment by JuhaO81** [comment] 2020-06-25 12:39
hmm I might try Swift Package Manager. Thx for the tip.

**Comment by craigrouse** [comment] 2020-06-25 12:44
@JuhaO81 Let us know how you get on. SPM is far quicker to build our library if you're able to use it!

Which version of the beta do you have? 
![image](https://user-images.githubusercontent.com/4818525/85721990-c5c6d980-b6e9-11ea-84df-7aca2b3016b5.png)

Xcode > About will give you the exact build number. Thanks!

**Comment by craigrouse** [comment] 2020-06-25 13:33
@JuhaO81 FYI, I've found that this is a Swift compiler/code optimizer bug. I've posted my findings on the Carthage issue page and also sent feedback to Apple. I've checked again with Swift Package manager and I'm definitely not seeing an issue there, even if the app is in Release mode, so I hope that's an acceptable workaround for the time being. Thanks again for taking the time to let us know about this.

**Comment by JuhaO81** [comment] 2020-06-25 13:39
Version 12.0 beta (12A6159)

**Comment by craigrouse** [comment] 2020-06-29 08:13
This is confirmed to be an Xcode bug: https://developer.apple.com/forums/thread/649918

Will leave this issue open for now for visibility, but there is nothing we can do until the Xcode issue is resolved.

**Comment by JuhaO81** [comment] 2020-07-30 12:33
SMP worked just fine! Thanks for the tip.

**Comment by JuhaO81** [comment] 2020-08-07 07:24
About Carthage vs SMP. We have used Carthage so that we compile the libs and commit them to git. This way we have prebuild libs and they don't need to be compiled every time on developers machines. 

I roughly calculated that compiling Tealium at my machine with SMP took over 2 minutes. This means two minutes extra wait time for every clean build. 

As result we hope Carthage support starts to work that we can switch back using it :)

**Comment by craigrouse** [comment] 2020-08-07 07:37
@JuhaO81 we have a few optimizations coming that should speed up compilation time. Hopefully the xcode bug affecting Carthage builds will be fixed before the final release of Xcode 12.

**Comment by denni01** [comment] 2020-09-21 17:23
@craigrouse, it looks like Apple has explicitly stated that the Valid Architectures build setting is no longer supported [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes) in the build system section. The supported path forward is to use Excluded Architectures build setting instead. This will allow the project to build with Carthage.

**Comment by JuhaO81** [comment] 2020-10-08 06:35
This is not anymore relevant to us. We moved to SPM.

**Comment by christinasund** [comment] 2020-10-21 21:04
This has been fixed in the `2.1.0` release, let us know of any other issues. Thanks

**Closed** 2020-10-21 21:03 UTC
Labels: blocked, external-bug
