### ISSUE TITLE
[TEALIUM SWIFT BUG]: TealiumConfig.swift line 185

### ISSUE THREAD

**Issue by pBoelck** [Tealium/tealium-swift#238] opened 2021-11-15 13:26 UTC
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: iOS 15.1.0
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 13.1
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]: 4.4.2
Dependency manager [None/Carthage/CocoaPods]:Swift Package
Dependency manager version: 

**Describe the bug**
Crashed: com.tealium.backgroundserialqueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

**Does a workaround exist?**
I cannot reproduce the error. I only see the crash in the crash logs.

**Expected behavior**
It doesn't crash.

**Screenshots**
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/52406129/141789589-315e4c83-9e13-47bf-a87a-d77b636552b0.png">

**Comment by Enricoza** [comment] 2021-11-30 15:51
Hi @pBoelck, thanks for the report and sorry for having you waiting so much.
We've been looking into this, but I have a few questions just to be sure we understand your current environment.

You said you have tealium library 4.4.2? Is it probably just a typo and you meant 2.4.2?
And also, you mentioned the crash is happening on iOS 15.1.0. Is it for all instances of the crash, or is it spread across different iOS versions?

**Comment by Enricoza** [comment] 2021-12-02 11:38
Hi again @pBoelck, we just released the version `2.5.1` of the library and it improves some threading issues that may have been the cause of this crash, so we think this issue may be solved.

I'm going to close this for now, but if you keep getting this crash after updating to 2.5.1 please reopen this and provide updated details where needed.

**Closed by Enricoza** 2021-12-02 11:38 UTC
