### ISSUE TITLE
Debug Error : Couldn't IRGen expression with Tealium 1.6.7

### ISSUE THREAD

**Issue by chrismcx** [Tealium/tealium-swift#82] opened 2019-02-13 14:19 UTC
I'm not able to debug my application using Tealium 1.6.7.
after a breakpoint, i launch "po UIApplication.shared" command and i have an error : 
```
(lldb) po UIApplication.shared
error: Couldn't IRGen expression, no additional error

```
Due to build delay from Carthage (25mn), i use the "carthage archive" command to zip my frameworks binaries and put it to a Nexus repository.

I do so with all other dependencies (RxSwift, ...) and i have no problems to debug.

I'm sure the problem comes from Tealium and to reproduce this issue : 
- launch XCode 10.1,
- create a new empty project (swift 4.2),
- link carthage binary framework (TealiumCore.framework) retrieved as binary from Nexus
- set breakpoint on AppDelegate at the end of didFinishLaunchingWithOptions function.
- run the application.
- on lldb prompt, call "po UIApplication.shared"

Thank you.

**Comment by craigrouse** [comment] 2019-02-13 21:03
@chrismcx Sorry you're having this issue. I have only just seen this, so haven't had time to test yet, but a quick search reveals this SO thread: https://stackoverflow.com/questions/43977271/lldb-couldnt-irgen-expression

Have you tried any of the suggestions on this thread? Thank you.

**Comment by jonwong-tealium** [comment] 2019-02-13 21:37
Hi @chrismcx . Are you able to test this without the archiving step to Nexus and retrieving binary from Nexus to help diagnose the issue? 

I've tried repeating your steps without Nexus as follows and I don't see the same error:

* launch XCode 10.1
* create a new empty project (Swift 4.2)
* Cartfile -> `github tealium/tealium-swift`
* `carthage update` (followed by bringing in TealiumCore, TealiumAppData, TealiumCollect)
* set breakpoint on AppDelegate at the end of didFinishLaunchingWithOptions function
* run the application
* on lldb prompt, call "po UIApplication.shared"
  * result: `<UIApplication: 0x7fc182c00c30>`

**Comment by chrismcx** [comment] 2019-02-14 08:10
Hi,
Indeed, by using carthage update from github locally and without retrieving binary from Nexus, it works (because carthage checkouts the project and build it).
What i don't understand is why my method (carthage update from github + carthage archive + send to nexus + change Cartfile to use nexus binary) doesn't work for this specific repository. I do the same with RxSwift, Fabric, Crashlytics, JSONWebToken... and i don't have this issue.

I am going to do some other tests but currently, i don't know what the problem is.

**Comment by jonwong-tealium** [comment] 2019-02-14 16:12
Hi @chrismcx . Have you tried your method 

> carthage update from github + carthage archive + send to nexus + change Cartfile to use nexus binary

with just Tealium and not with RxSwift, Fabric, etc?

**Comment by chrismcx** [comment] 2019-02-14 17:08
Yes i did.

I still have the issue : 
```
(lldb) po UIApplication.shared
error: Couldn't IRGen expression, no additional error

```
To be more precise, if i build from my own computer and upload to Nexus, this is Okay.
If i build with another "really similar" computer, i have the issue. Every other packages are built on this another computer and it works. This is why i'm wondering the problem is related to the project configuration.

**Comment by craigrouse** [comment] 2019-07-22 12:33
@chrismcx I am closing this issue for now, since it's not something we can reproduce internally.

I believe we are right to leave our "strip debug symbols" setting set to NO, since the symbols will be stripped later on when the app is archived. I've also checked a few other frameworks, and found this to be fairly standard.

I'm still not sure why changing this specific setting had the effect that it did for you, but glad that it's working. Let us know if you have any further issues.

**Closed by craigrouse** 2019-07-22 12:33 UTC
