### ISSUE TITLE
Unexpected fields even after disabling all Collectors

### ISSUE THREAD

**Issue by ericklborges** [Tealium/tealium-swift#328] opened 2024-03-13 14:36 UTC
### **Your Environment**

- **iOS Version**: 17.4
- **Xcode version**: 15.2.0
- **Swift version**: 5.9
- **Tealium Swift library version**: 2.10.1 
- **Dependency manager**: SPM
- **Dependency manager version**: Xcode 15.2.0

### **Describe the bug**
I have disabled every Collector this way:
```swift
config.collectors = []
```

After doing that, I expected that only the fields I added to my custom events would be sent to the dashboard. But instead, I see some extra fields that I don't know where they come from, they are listed in the drop down bellow.

<details>
<summary>Fields</summary>

1. app_build
2. app_name
3. app_rdns
4. app_version
5. tealium_visitor_id
6. tealium_account
7. tealium_profile
8. tealium_environment
9. tealium_datasource
10. tealium_visitor_id
11. tealium_random
12. was_queued
13. timestamp
14. timestamp_local
15. timestamp_offset
16. timestamp_unix
17. timestamp_unix_milliseconds

</details>

Looking into the Android documentation I found Collectors that are responsible to log these exact same fields, but these collectors doesn't seem to be present or configurable on iOS. They are:

<details>
<summary>
<a href="https://docs.tealium.com/platforms/android-kotlin/data-layer/#app-collector">App Collector</a>
</summary>

1. app_build
2. app_name
3. app_rdns
4. app_version
5. tealium_visitor_id

</details>

<details>
<summary>
<a href="https://docs.tealium.com/platforms/android-kotlin/data-layer/#tealium-collector">Tealium Collector</a>
</summary>

6. tealium_account
7. tealium_profile
8. tealium_environment
9. tealium_datasource
10. tealium_visitor_id
11. tealium_random
12. was_queued

</details>

<details>
<summary>
<a href="https://docs.tealium.com/platforms/android-kotlin/data-layer/#time-collector">Time Collector</a>
</summary>

13. timestamp
14. timestamp_local
15. timestamp_offset
16. timestamp_unix
17. timestamp_unix_milliseconds

</details>

### **Does a workaround exist?**
N/A

### **To Reproduce**
1. Disable all Collectors 
2. Track any custom event with your custom parameters
3. Check the extra parameters that get to Tealium Dashboard

### **Expected behavior**
That only the parameters added to my custom events show in Tealium Dashboard.
Is there any way how to disable this data from being sent to the Dashboard on iOS?

### **Screenshots**
N/A

### **Additional context**
N/A

**Comment by craigrouse** [comment] 2024-03-13 16:24
@ericklborges The Tealium account and profile data is essential, otherwise your data wouldn't be directed to your Tealium profile correclty. The information about the app is perhaps less essential, but there is currently no way to disable that module, and that is by design. We will consider making it optional in future, but that would be a breaking change for many customers, so it needs careful consideration. The timestamp data is essential for most analytics tools, which is why it's also not able to be removed. You're right that there's a difference between that way our Android and Swift libraries handle this data, and it's something we aim to consolidate in future, but again, it would be a breaking change, and difficult to implement without causing problems for customers who already have the SDKs in their production apps. Since this is by design and isn't a defect, I'm going to close the issue for now, but we will carefully consider your feedback for future releases. Please contact our support team if you need to discuss this further ([support link](https://my.tealiumiq.com/?_gl=1*1w1wg8i*_gcl_aw*R0NMLjE2MjA3NjE4NzQuQ2p3S0NBancxdWlFQmhCekVpd0FPOUJfSFotVXp5NkFiNEtaSm4yVDJaOWlEQ0NzdXNPYjdqZFhJa3pyanVjUTNTSHI0a3FxbWg1NXdSb0NRNzhRQXZEX0J3RQ..)).

**Closed** 2024-03-13 16:25 UTC
