### ISSUE TITLE
[TEALIUM SWIFT BUG]: TealiumViews have same value for tealium_event and screen_title

### ISSUE THREAD

**Issue by jandro-es** [Tealium/tealium-swift#172] opened 2021-01-21 13:57 UTC
**Your Environment**
EventStream
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: All
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: All
Swift version [e.g. 4.2]: 5.2
Tealium Swift library version [e.g. 1.6.7]: 2.2.2
Dependency manager [None/Carthage/CocoaPods]: Cocoapods
Dependency manager version: 1.10.0

**Describe the bug**
Since the migration to the version 2.x of the Library we're not able to identify when an event is a ScreenView as both, the `tealium_event` and `screen_title` properties have the same value.

Previously we were sending `screen_view` in the `tealium_event` property so we could use it as a constant to differentiate the type of event in EventStream. Since the update, we haven't found a way of doing this.

**Does a workaround exist?**
Not found at the moment.

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. Any screen view event in an iOS build with Library > 2.x

**Expected behavior**
It may be, but we don't know how to address it.

**Screenshots**
<img width="533" alt="Screenshot 2021-01-21 at 13 58 44" src="https://user-images.githubusercontent.com/1234663/105360718-d04e4080-5bf0-11eb-8a6d-754e97ab165d.png">

**Additional context**

**Comment by craigrouse** [comment] 2021-01-21 14:17
@jandro-es Thanks for raising this. I've already been speaking to your support engineer about this. This is expected behavior; for events, tealium_event gets the value of the event name, and for screen views, it gets the value of the screen name. Could you please confirm which SDK version you were using prior to the upgrade so we can investigate further? Thank you.

**Comment by jandro-es** [comment] 2021-01-21 14:21
Thanks a lot, @craigrouse. Yes, of course, we were using `1.9.3`. Previously we were passing `screen_view` as the name of the event for screen views, but I don't think we have a way of doing the same now.

Thanks a lot again,

**Comment by Matthias-Jirmann** [comment] 2021-01-21 14:31
Hey Craig, 
as an example for custom_clicks the normal behaviour still works as shown in the attached screenshot. Please see the variables `screen_title` and `tealium_event`
![Screenshot 2021-01-21 at 14 25 16](https://user-images.githubusercontent.com/25385132/105364057-9e3edd80-5bf4-11eb-839b-e469847560a6.png)

As comparison please see an example of a page_view:
![Screenshot 2021-01-21 at 14 27 18](https://user-images.githubusercontent.com/25385132/105364200-c9c1c800-5bf4-11eb-994b-988c91bb33e4.png)

As you can see the tealium_profile no longer differs to the screen_title. However we are using `tealium_event: screen_view` to identify screen_views and apply them to the correct event feed.

**Comment by craigrouse** [comment] 2021-01-21 15:54
@Matthias-Jirmann Just to clarify, you are directly passing the keyname "tealium_event" as part of the data layer? We don't expect customers to use the tealium_event key directly - it is normally set by the SDKs or JavaScript tags (in the case of a web deployment). I'd suggest if possible switching to a different keyname, but I will see if we can find a workaround for you in the meantime

Thanks.

**Comment by Matthias-Jirmann** [comment] 2021-01-21 16:02
@jandro-es are we passing the `tealium_event` parameter in the payload or is that from the Tealium SDK automatically?

**Comment by jandro-es** [comment] 2021-01-21 18:15
@Matthias-Jirmann no, we're not passing it in the payload. For Events, we call:
```swift
TealiumEvent("custom_click", dataLayer: payload)
```
which internally assigns `custom_click` to `tealium_event`. But for views, we call:
```switt
TealiumView(screenName, dataLayer: payload)
```
wich assings `screenName` to `tealium_event` and `screen_title`.

Hope it helps

**Comment by Matthias-Jirmann** [comment] 2021-01-21 20:14
@craigrouse So it seems from @jandro-es response that we are not actually setting `tealium_event` manually but that it is send in the payload automatically. It sounded from your last message like this is not expected behaviour.

**Comment by craigrouse** [comment] 2021-01-25 10:14
@Matthias-Jirmann @jandro-es Apologies for the delay - I was off on Friday. I understand what you're saying now. However, this is expected behavior - tealium_event is defined as the name of the event or the name of the screen. Bear with me - I'm speaking to your support engineer to see if we can come up with a workaround for you.

**Comment by craigrouse** [comment] 2021-04-20 15:17
Closing this issue for now, since this is expected behavior. In [2.3.0](https://github.com/Tealium/tealium-swift/releases/tag/2.3.0), we added an extra variable `tealium_event_type` so it's easy to identify views vs events. Please let us know if you have any further issues.

**Closed by craigrouse** 2021-04-20 15:17 UTC
